# Generated by Django 3.2.14 on 2022-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_productorder_carry_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='state',
            field=models.CharField(choices=[('ESPERA', 'E'), ('PREPARACION', 'P'), ('FINALIZADO', 'F')], default='ESPERA', max_length=11),
        ),
    ]
